import Head from "next/head";
import { api } from "@/utils/api";
import { useState } from "react";
import TweetPost from "@/components/post/tweet";
import { PageLayout } from "@/components/layout";
import { Button } from "@material-tailwind/react";

export default function Home() {
  const { mutateAsync, data } = api.threadslogin.login.useMutation();
  const { mutateAsync: post } = api.threadslogin.post.useMutation();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const onsubmit = () => {
    mutateAsync({ username, password }).then(() => {
      alert(data?.token);
      if (data) {
        const token = data.token;
        if (token) {
          localStorage.setItem("token", token);
          localStorage.setItem("username", username);
        }
      }
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <div className="p-4 flex gap-3">
          <input
            onChange={(e) => {
              setUsername(e.target.value);
            }}
            type="text"
            placeholder="username"
            className="rounded-md border py-2 px-3"
          />
          <input
            onChange={(e) => {
              setPassword(e.target.value);
            }}
            type="password"
            placeholder="password"
            className="rounded-md border py-2 px-3"
          />
          <Button onClick={()=>onsubmit}>
            Submit
          </Button>
        </div>
        <TweetPost />
      </PageLayout>
    </>
  );
}
