import Head from "next/head";
import { api } from "@/utils/api";
import { useEffect, useState } from "react";
import TweetPost from "@/components/post/thread";
import { PageLayout } from "@/components/layout";
import { Button } from "@material-tailwind/react";
import Header from "@/components/header";
import Loading from "@/components/loading";

export default function Home() {
  const { mutateAsync, data, isLoading } = api.threadslogin.login.useMutation();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");


  const onsubmit = () => {
    mutateAsync({ username, password }).then(() => {
      alert(data?.token);
      if (data) {
        const token = data.token;
        if (token) {
          localStorage.setItem("token", token);
          localStorage.setItem("username", username);
        }
      }
    });
  };

  useEffect(() => {
    const storedUsername = localStorage.getItem('username');
    if (storedUsername) {
      setUsername(storedUsername);
    }
  }, []);



  if (typeof window !== 'undefined') {
  const password = localStorage.getItem("password");
  const username = localStorage.getItem("username");
  }

  return (
    <>
      <Head>
        <title>Thread Web | by Swaraj Bachu</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <Header/>
        <div className="p-4 flex gap-3">
          <input
            onChange={(e) => {
              setUsername(e.target.value);
            }}
            type="text"
            placeholder="username"
            value={username}
            className="rounded-md border py-2 px-3"
          />
          <input
            onChange={(e) => {
              setPassword(e.target.value);
            }}
            type="password"
            placeholder="password"
            value={password}
            className="rounded-md border py-2 px-3"
          />
          <Button className="bg-black" onClick={onsubmit}>
            {isLoading ? <Loading/> : "Login"}
          </Button>
        </div>
        <TweetPost />
      </PageLayout>
    </>
  );
}
